part of 'daily_attendance_cubit.dart';

/// Represents the different states for the daily attendance feature.
///
/// This class is a sealed union type generated by the `freezed` package,
/// which ensures that the state is immutable and provides helpful methods
/// for pattern matching and copying.
@freezed
abstract class DailyAttendanceState with _$DailyAttendanceState {
  /// The initial state of the cubit, before any data has been loaded or fetched.
  /// This is the starting point of the state machine.
  const factory DailyAttendanceState.initial() = _Initial;

  /// A state indicating that data is currently being fetched from the server.
  /// This is typically used to show a loading indicator in the UI.
  const factory DailyAttendanceState.loading() = _Loading;

  /// Represents a state where no attendance data is available for the user.
  /// This could be because the user has not yet started their attendance, or
  /// there are no records in the database.
  const factory DailyAttendanceState.emptyData() = _EmptyData;

  /// The state indicating that daily attendance data has been successfully loaded.
  ///
  /// This state holds the core attendance information for the day, as well as
  /// flags for the user's check-in, check-out, and post statuses.
  const factory DailyAttendanceState.hasData({
    /// The main attendance data for the current day.
    DailyAttendance? dailyAttendance,

    /// A flag indicating whether the initial attendance for the day has been posted.
    @Default(false) bool hasPost,

    /// A flag indicating whether the user has checked in for the day.
    @Default(false) bool hasCheckIn,

    /// A flag indicating whether the user has checked out for the day.
    @Default(false) bool hasCheckOut,

    /// The timestamp of the last time the data was updated.
    /// This is used for caching and determining if the data is stale.
    DateTime? lastUpdate,
  }) = _HasData;

  /// A state representing that an error occurred while fetching or processing
  /// attendance data.
  ///
  /// The [errorMessage] parameter contains a description of the error that can
  /// be displayed to the user.
  const factory DailyAttendanceState.failure(String errorMessage) = _Failure;
}
